### ISSUE TITLE
We are now an Organization

### ISSUE THREAD

**Issue by emreakay** [magefly/CodeIgniter-Aauth#189]
Hi My dear Aauth Community;

I have just transferred Our Project to AkaySoftware organization thus our project will grow up and spread faster and also we will be able to use some tools more effectively.

@REJack will release v3 soon, we all have been looking forward to see v3.

Thank you for all for your self-sacrificing contributions. We are now one of the most favorite Auth Library between Codeigniter Programmers, I always get good feedbacks. I am sure we will be going on growing up, 

Sincerely.

**Comment by AzrielOmega** [comment]
Today is first day of Lunar New Year and this news make me feel great. Keep up the good work, you guys are totally awesome.

**Comment by nedevl** [comment]
Documentation is missing.

**Comment by REJack** [comment]
@nedevl nope its over the [Wiki](https://github.com/AkaySoftware/CodeIgniter-Aauth/wiki)
