### ISSUE TITLE
List of group permissions:

### ISSUE THREAD

**Issue by oniricosistemas** [magefly/CodeIgniter-Aauth#195]
You could add a function which returns the list of permissions assigned to a group. For example:
$ This-> aauth-> list_perm_group ($ id);
$ Id = id group;
And return an array with the id and permission name:
[0] => array ('id' => 12, 'name' => 'Print_Report'),
[1] => array ('id' => 2, 'name' => 'Delete User'),

Sorry for my bad English lol
Regards

**Comment by oniricosistemas** [comment]
I have added the following code to obtain the list of permissions that has a particular group, I hope you like it and add it to the library
```php
         /**
	 * List Permissions by Group
	 * List all permissions by Group
	 * @return object Array of permissions
	 */
	public function list_perms_group($id) {
		if(empty($id)){
			return false;
		}

		$this->aauth_db->select('*');
		$this->aauth_db->from($this->config_vars['perms']);
		$this->aauth_db->join($this->config_vars['perm_to_group'], "perm_id = ".$this->config_vars['perms'].".id");
		$this->aauth_db->where($this->config_vars['perm_to_group'].'.group_id', $id);

		$query = $this->aauth_db->get();
		if ($query->num_rows() == 0)
			return FALSE;

		return $query->result();
	}
```

**Comment by REJack** [comment]
Added in master as list_group_perms($group_par)
