### ISSUE TITLE
New Place for Us! 

### ISSUE THREAD

**Issue by emreakay** [magefly/CodeIgniter-Aauth#196]
Hello My Dear Aauth Community;

I have just transferred Our Project to my new company "Magefly". 

We will be developing our project with both you - Aauth Community- and my colleagues.

Thank you for all for your self-sacrificing contributions. We are now one of the most favorite Auth Library between Codeigniter Programmers, I always get good feedbacks. I am sure we will be going on growing up,

Sincerely.

**Comment by AzrielOmega** [comment]
Thank you for staying with us and all the hard work to give us the best Auth library of CodeIgniter. You are the best.

**Comment by foxmedo** [comment]
you still working on this lib or we must search something else ??

we can help you to improve this lib, but you must be present, waiting for your feedback ASAP

Regards

**Comment by REJack** [comment]
@foxmedo I'm still work on this library but i have much work at the moment from my Job I'll try to finish in the next weeks v3.0.0-beta1 with all original functions 😄 then i can start with the new features.

**Comment by foxmedo** [comment]
any new ???

**Comment by REJack** [comment]
@foxmedo I've stuck a the moment much in some Jobs, but i'll try to push my changes in the next week. The PHPUnit testing is sometimes quite difficult ^^ and i want to get 100%
