### ISSUE TITLE
Database field pass in aauth_users to short

### ISSUE THREAD

**Issue by WagnerSystems** [magefly/CodeIgniter-Aauth#201]
Searched for hours today, why I couldn't login in with aauth. In my configuration the field pass in the users table was to small to hold the password hash. In creasing it too 100 characters did the job.
I'm using Version 2.2.0, installed from tar.gz

**Comment by REJack** [comment]
Thats correct if you changed the password hash method, for the old hash method (sha256) you need 64 chars and for the new one BCrypt (`use_password_hash` = TRUE) you need only 60 chars.

**Comment by WagnerSystems** [comment]
Yes I agree, but there is an database creation script in the 2.2.0 tar.gz file at http://codeigniter-aauth-test.readthedocs.io/en/latest/downloads.html which only creates a field with 50 chars. This is not a complaining, I just do not want others to stumple in the same mistake than I did.

**Comment by REJack** [comment]
Damn i didn't reconized that my first try of an real documentation is still online 😄, i need to remove the old docs.

But the version v2.2.0 is really old, you should use v2.5.12 (latest).
This issue has been already fixed in v2.3.0.
