### ISSUE TITLE
TOTP login bug

### ISSUE THREAD

**Issue by adampweb** [magefly/CodeIgniter-Aauth#206]
I found a bug in the next file: **application/libraries/Aauth.php**
line 188 and 189:
with bug (**_this bug is prevent the totp-verification_**):
_if($this->config_vars['totp_active'] == TRUE AND $this->config_vars['totp_only_on_ip_change'] == FALSE AND $this->config_vars['totp_two_step_login_active'] == **FALSE**){
    if($this->config_vars['totp_two_step_login_active'] == **TRUE**){_

**I corrected it and that working correctly:**
188 and 189 line: 
_if($this->config_vars['totp_active'] == TRUE AND $this->config_vars['totp_only_on_ip_change'] == FALSE AND $this->config_vars['totp_two_step_login_active'] == **TRUE**){
    if($this->config_vars['totp_two_step_login_active'] == **TRUE**){_

**Comment by REJack** [comment]
Thanks for reporting the bug, I'll fix this later.

**Comment by REJack** [comment]
I've fixed it in the master branch, you can test it 😄
