### ISSUE TITLE
How to activate TOTP by user?

### ISSUE THREAD

**Issue by adampweb** [magefly/CodeIgniter-Aauth#207]
If I activate OTP authentication in a configuration, I activate this for all users.
Is it possible to configure two-step authentication per user?

So far, I have the only idea: I extend the "Aauth" lib and then overwrite the login method in new lib.

Can it be solve simpler?

**Comment by REJack** [comment]
First sry for the long delay :/

It works already per user as an optional feature it's not required for any user. 
If you activate OTP in the config then you give all users the abilty to setup OTP, not every user need OTP but anyone can activate it for it self. If any user saved a OTP secret in his user profile only then the user need to use the OTP Code to login.
