### ISSUE TITLE
create_user() with set_user_var()

### ISSUE THREAD

**Issue by SirTom76** [magefly/CodeIgniter-Aauth#209]
Is it possible to set user variables together with the user registration? I would like to set the first and last name with the Registration.

`$this->aauth->create_user($mail, $pw, $user);
$this->aauth->set_user_var("first_name",$fn);
$this->aauth->set_user_var("last_name",$ln);	`

This will not work. Thanks for your help.

**Comment by REJack** [comment]
Your code should look like this:
```
$user_id = $this->aauth->create_user($mail, $pw, $user);
$this->aauth->set_user_var("first_name", $fn, $user_id); 
$this->aauth->set_user_var("last_name", $ln, $user_id);
```

regards REJack

**Comment by SirTom76** [comment]
It works! Thanks!!!

**Comment by REJack** [comment]
Perfect, I'll close this issue 😄 
Optimal, ich schließ das hier mal xD
