### ISSUE TITLE
Reset password with empty or unkown verification code

### ISSUE THREAD

**Issue by chief-kh** [magefly/CodeIgniter-Aauth#210]
$this->aauth->reset_password('');
Does not produce any errors

**Comment by REJack** [comment]
Yep, that's true we need to add a error message for this behavior.

I'll add this into the v2.5 in the next days.

**Comment by REJack** [comment]
I've fixed it/added a new error message for it, you can test it it's pushed into the master branch.

**Comment by REJack** [comment]
@scombat @mylastof @suhindra @pars0097 @mirivlad @terrylinooo @siarlex @perenstrom It would be great if you could look over the language files that you added/changed to translate the new lang line. 😄
