### ISSUE TITLE
missing get_perm($perm_id)

### ISSUE THREAD

**Issue by SirTom76** [magefly/CodeIgniter-Aauth#211]
I miss a function for get all parameters from a permission by id.I would like to crate a admin backend and need this function to edit a permission. Is this feature missing?

Thanks for your help
Tom

**Comment by REJack** [comment]
Oh shit, thats true a get_perm($perm_id) is not there :/ 

I'll add this into the v2.5 in the next days.

**Comment by SirTom76** [comment]
and get_group($group_id), too ;-)

`public function get_perm($perm_id) {

		$this->aauth_db->where('id', $perm_id);
		$query = $this->aauth_db->get($this->config_vars['perms']);
		
		if ($query->num_rows() == 0)
			return FALSE;
		
		$row = $query->row();
						
		return $row;
	}
	
	public function get_group($group_id) {

		$this->aauth_db->where('id', $group_id);
		$query = $this->aauth_db->get($this->config_vars['groups']);
		
		if ($query->num_rows() == 0)
			return FALSE;
		
		$row = $query->row();
						
		return $row;
	}`

By the way, is delete_perm($perm_par) workin?
In the commentary you wrote "//not ok"

**Comment by REJack** [comment]
I've added both functions (`get_perm($perm_par)` & `get_group($group_par)`), you can test it it's pushed into the master branch.

**Comment by SirTom76** [comment]
Thanks! It is working ;-)

**Comment by REJack** [comment]
Sweet 😄, I'll create a release in the next days.
