### ISSUE TITLE
all permissions from one group

### ISSUE THREAD

**Issue by SirTom76** [magefly/CodeIgniter-Aauth#212]
How can I list all permissions from one group?

Thanks 
Tom

**Comment by REJack** [comment]
I've added `get_group_perms($group_par)` & `get_user_perms($user_id = FALSE)`, you can test it it's pushed into the master branch.

**Comment by SirTom76** [comment]
Thanks! It is working ;-)

**Comment by REJack** [comment]
Sweet 😄, I'll create a release in the next days.
