### ISSUE TITLE
create_user(...) without verification

### ISSUE THREAD

**Issue by SirTom76** [magefly/CodeIgniter-Aauth#213]
The verification code is for users created by the registration form. Is it possible to create users by the administrator, without generating a verification code?

Thanks
Tom

**Comment by REJack** [comment]
If you create a User as Admin, it won't set a verification code.

We use this check in `create_user()`:
`if($this->config_vars['verification'] && !$this->is_admin()){`

**Comment by SirTom76** [comment]
Oh, I don't see that part. It is working, thanks!

**Comment by REJack** [comment]
Perfect then I'll close this issue.
