### ISSUE TITLE
Russian letters in the username

### ISSUE THREAD

**Issue by StAlKeRxXl** [magefly/CodeIgniter-Aauth#219]
Hello!
How can I use Russian letters in a name?
I tried to add them to the array in conf aauth.php- but it does not work ..
Will you provide the correct syntax?

**Comment by REJack** [comment]
Could you post your tested aauth config vars?

Does the russian language work with the UTF-8 Charset? I've never used russian sry

**Comment by StAlKeRxXl** [comment]
`'additional_valid_chars' => array("А", "Б", "В"),`

Yes, working with UTF

**Comment by REJack** [comment]
I've tested your additional_valid_chars and it works, I've created a test user with the name `TestUserБ` 😄 and if I'm add `Ж` to the array it allows also to rename the username to `TestUserБAЖ`. 

That's strange :/ Did you recived a error on user creation?

**Comment by StAlKeRxXl** [comment]
Ok, I'll check today again .. Maybe my little php experience is the cause of the problem =)
Wonderful library!

**Comment by REJack** [comment]
Ok nice, if you have some troubles with CI or Aauth let me know :D

And if you search an better alternative to CI's view loader, i recommend the [Twig](https://twig.symfony.com/) Template Engine with [Twiggy](https://github.com/REJack/codeigniter-twiggy/) for CI ^^

P.S.: You not need `A` or `В` in your array 😄 they look like normal alphanumeric characters.

**Comment by StAlKeRxXl** [comment]
Ok, tnx!
