### ISSUE TITLE
Groups & Subgroups - possible endless loop

### ISSUE THREAD

**Issue by chland** [magefly/CodeIgniter-Aauth#221]
Lets say you've got 3 groups:

- Group A
- Group B
- Group C

Now you add B as a subgroup to A. Then you add C as a subgroup to B and finally you add Group A (!!!) as a subgroup to C.

If you then use is_allowed() to check if a user who is a member of Group A has a certain permission, the code will end up in an endless loop going through all groups over and over until the server times out or the server crashes.

The add_subgroup()-function should prevent these situations.

**Comment by REJack** [comment]
Oh thanks for reporting this issue, I've looked over add_subgroup() I'll fix this in the next days.

**Comment by REJack** [comment]
Issue closed, changes committed in master repo
