### ISSUE TITLE
No transaction-handling

### ISSUE THREAD

**Issue by chland** [magefly/CodeIgniter-Aauth#225]
Right now, the library isn't using transaction-handling. IMHO it would be a good idea to add it to all functions where multiple updates/deletes are executed to prevent any problems if the db-server dies halfway through deleting stuff. For example in `delete_user()`, `delete_group()` or `delete_perm()`, multiple delete-queries are executed.

I started to add some basic transaction-handling to the code and can create a PR from my changes later today when i'm done.

**Comment by REJack** [comment]
That's a great idea and your changes looks good and works.

**Comment by REJack** [comment]
Issue closed
