### ISSUE TITLE
generate list list_perms() 

### ISSUE THREAD

**Issue by asifagaria** [magefly/CodeIgniter-Aauth#231]
i have a problem to generate list_perms() 

i dont now how is admin access or other access please help 
sir to view list_perms() $userid

**Comment by REJack** [comment]
You want a list of all perms from an user?

**Comment by asifagaria** [comment]
yes

**Comment by asifagaria** [comment]
sir is aauth v3.0 is complete done

**Comment by REJack** [comment]
There is a function `get_user_perms($user_id)`.

Aauth v3 is not done yet only the models are done, I'm working on the Library and tests.

**Comment by asifagaria** [comment]
thanks
