### ISSUE TITLE
login with name error

### ISSUE THREAD

**Issue by asifagaria** [magefly/CodeIgniter-Aauth#232]
'login_with_name'                => ture,

give Error
Severity: Notice

Message: Use of undefined constant ture - assumed 'ture'

Filename: config/aauth.php

Line Number: 129

Backtrace:

File: /var/www/html/application/config/aauth.php
Line: 129
Function: _error_handler

**Comment by REJack** [comment]
It’s true not ture!!!!

Mit freundlichen Grüßen
Raphael Jackstadt

Von meinem iPhone gesendet
