### ISSUE TITLE
is_banned function issue

### ISSUE THREAD

**Issue by jmikerq** [magefly/CodeIgniter-Aauth#233]
https://github.com/magefly/CodeIgniter-Aauth/blob/7ae5ef5fbc424b3e75bec3389a483d95e5cd5bc8/application/libraries/Aauth.php#L1072

I understand that your is_banned function checks if an existing user is banned. However, in a case where if the user doesn't exist in the system, this function will return FALSE, which means this non-existing user is not banned. 

For security, I think it would be better to return TRUE for all users not found.

**Comment by REJack** [comment]
That's a good idea, I'll change this in the next days :smile:

**Comment by REJack** [comment]
Issue closed, changes committed in master repo
