### ISSUE TITLE
Aauth Advanced example

### ISSUE THREAD

**Issue by foxmedo** [magefly/CodeIgniter-Aauth#237]
Hello All, 

I'm Looking for exemples using Aauth with Roles (Groups) management somthing really advanced

Waiting for your feedbacks 

B.R

**Comment by emreakay** [comment]
hi;

you see datailed doc from wiki 

https://github.com/magefly/CodeIgniter-Aauth/wiki/4)-User-Operations
https://github.com/magefly/CodeIgniter-Aauth/wiki/5)-Group-Operations
