### ISSUE TITLE
Login Attempts

### ISSUE THREAD

**Issue by marcoscssno** [magefly/CodeIgniter-Aauth#30]
Why does _login_attempts_ is updated even if login was successfully?

**Comment by Firefly16** [comment]
I don't know if you will read this but, is there a way to print the login attemps? I tried with this $login_attempts because there is some $data['login_attempts'] in the aauth library, but $login_attempts doens't exist apparently :/

**Comment by REJack** [comment]
You can check the login attempts over any MySQL tool.
Which type of login attempt you do? (Wrong Mail or Wrong Password)?

**Comment by Firefly16** [comment]
Ho, this isn't the same for the two?

So i need wrong password with good email ^^

**Comment by REJack** [comment]
Wrong Password works 
Wrong Mail doesn't work (no user to set login_attempt) that's why i created the issue #137

**Comment by Firefly16** [comment]
But, i don't understand, u say 'You can check the login attempts over any MySQL tool.', but to be display with a mysql tool they need to be stored somewhere in DB no? I don't find the variable to display :x

**Comment by REJack** [comment]
The `login_attempts` field is in the user-table

**Comment by Firefly16** [comment]
I'm so blind -_-

Sorry for that ^^'

**Comment by REJack** [comment]
np for that im a Collaborator :smile:
